// New Standard Translator System - Truth Words & Replacements
const translations = {
  en: {
    // Core Navigation
    home: "Home",
    login: "Login", 
    register: "Register",
    dashboard: "Dashboard",
    products: "Products",
    orders: "Orders",
    profile: "Profile",
    logout: "Logout",
    
    // Truth Words - About Others & Integrity
    truth: "Truth",
    honesty: "Honesty",
    integrity: "Integrity",
    transparency: "Transparency",
    fairness: "Fairness",
    respect: "Respect",
    trust: "Trust",
    authenticity: "Authenticity",
    accountability: "Accountability",
    responsibility: "Responsibility",
    community: "Community",
    collaboration: "Collaboration",
    support: "Support",
    empowerment: "Empowerment",
    equality: "Equality",
    justice: "Justice",
    service: "Service",
    dedication: "Dedication",
    commitment: "Commitment",
    excellence: "Excellence",
    quality: "Quality",
    value: "Value",
    principles: "Principles",
    ethics: "Ethics",
    morals: "Morals",
    character: "Character",
    virtue: "Virtue",
    wisdom: "Wisdom",
    knowledge: "Knowledge",
    understanding: "Understanding",
    compassion: "Compassion",
    kindness: "Kindness",
    generosity: "Generosity",
    patience: "Patience",
    perseverance: "Perseverance",
    courage: "Courage",
    strength: "Strength",
    resilience: "Resilience",
    hope: "Hope",
    faith: "Faith",
    love: "Love",
    peace: "Peace",
    unity: "Unity",
    harmony: "Harmony",
    balance: "Balance",
    growth: "Growth",
    learning: "Learning",
    teaching: "Teaching",
    sharing: "Sharing",
    giving: "Giving",
    receiving: "Receiving",
    gratitude: "Gratitude",
    humility: "Humility",
    forgiveness: "Forgiveness",
    reconciliation: "Reconciliation",
    healing: "Healing",
    restoration: "Restoration",
    renewal: "Renewal",
    transformation: "Transformation",
    
    // About Others - Building Relationships
    connection: "Connection",
    relationship: "Relationship",
    friendship: "Friendship",
    partnership: "Partnership",
    cooperation: "Cooperation",
    teamwork: "Teamwork",
    communication: "Communication",
    listening: "Listening",
    empathy: "Empathy",
    understanding: "Understanding",
    acceptance: "Acceptance",
    tolerance: "Tolerance",
    inclusion: "Inclusion",
    belonging: "Belonging",
    welcome: "Welcome",
    hospitality: "Hospitality",
    kindness: "Kindness",
    compassion: "Compassion",
    care: "Care",
    concern: "Concern",
    interest: "Interest",
    attention: "Attention",
    presence: "Presence",
    engagement: "Engagement",
    interaction: "Interaction",
    conversation: "Conversation",
    dialogue: "Dialogue",
    discussion: "Discussion",
    exchange: "Exchange",
    
    // Truth in Action - Practical Applications
    truthfulness: "Truthfulness",
    sincerity: "Sincerity",
    genuineness: "Genuineness",
    authenticity: "Authenticity",
    reliability: "Reliability",
    dependability: "Dependability",
    consistency: "Consistency",
    faithfulness: "Faithfulness",
    loyalty: "Loyalty",
    devotion: "Devotion",
    passion: "Passion",
    enthusiasm: "Enthusiasm",
    motivation: "Motivation",
    inspiration: "Inspiration",
    creativity: "Creativity",
    innovation: "Innovation",
    improvement: "Improvement",
    progress: "Progress",
    achievement: "Achievement",
    success: "Success",
    victory: "Victory",
    triumph: "Triumph",
    accomplishment: "Accomplishment",
    fulfillment: "Fulfillment",
    satisfaction: "Satisfaction",
    contentment: "Contentment",
    joy: "Joy",
    happiness: "Happiness",
    bliss: "Bliss",
    ecstasy: "Ecstasy",
    
    // Truth in Business - Professional Ethics
    professionalism: "Professionalism",
    expertise: "Expertise",
    competence: "Competence",
    skill: "Skill",
    mastery: "Mastery",
    craftsmanship: "Craftsmanship",
    quality: "Quality",
    excellence: "Excellence",
    standards: "Standards",
    guidelines: "Guidelines",
    policies: "Policies",
    procedures: "Procedures",
    protocols: "Protocols",
    bestPractices: "Best Practices",
    code: "Code",
    conduct: "Conduct",
    behavior: "Behavior",
    attitude: "Attitude",
    mindset: "Mindset",
    approach: "Approach",
    method: "Method",
    technique: "Technique",
    strategy: "Strategy",
    planning: "Planning",
    organization: "Organization",
    management: "Management",
    leadership: "Leadership",
    guidance: "Guidance",
    mentorship: "Mentorship",
    
    // Truth in Community - Social Impact
    service: "Service",
    contribution: "Contribution",
    impact: "Impact",
    influence: "Influence",
    legacy: "Legacy",
    heritage: "Heritage",
    tradition: "Tradition",
    culture: "Culture",
    identity: "Identity",
    purpose: "Purpose",
    mission: "Mission",
    vision: "Vision",
    goals: "Goals",
    objectives: "Objectives",
    targets: "Targets",
    milestones: "Milestones",
    benchmarks: "Benchmarks",
    metrics: "Metrics",
    results: "Results",
    outcomes: "Outcomes",
    benefits: "Benefits",
    advantages: "Advantages",
    opportunities: "Opportunities",
    potential: "Potential",
    capacity: "Capacity",
    capability: "Capability",
    ability: "Ability",
    talent: "Talent",
    gift: "Gift",
    blessing: "Blessing",
    fortune: "Fortune",
    prosperity: "Prosperity",
    abundance: "Abundance",
    wealth: "Wealth",
    richness: "Richness",
    
    // Truth in Nature - Agricultural Wisdom
    nature: "Nature",
    earth: "Earth",
    soil: "Soil",
    water: "Water",
    sun: "Sun",
    rain: "Rain",
    seasons: "Seasons",
    cycles: "Cycles",
    growth: "Growth",
    harvest: "Harvest",
    planting: "Planting",
    cultivation: "Cultivation",
    nurturing: "Nurturing",
    stewardship: "Stewardship",
    sustainability: "Sustainability",
    environment: "Environment",
    conservation: "Conservation",
    preservation: "Preservation",
    biodiversity: "Biodiversity",
    ecosystem: "Ecosystem",
    balance: "Balance",
    harmony: "Harmony",
    interdependence: "Interdependence",
    connection: "Connection",
    
    // Truth in Spirit - Higher Values
    spirit: "Spirit",
    soul: "Soul",
    heart: "Heart",
    mind: "Mind",
    consciousness: "Consciousness",
    awareness: "Awareness",
    enlightenment: "Enlightenment",
    wisdom: "Wisdom",
    insight: "Insight",
    intuition: "Intuition",
    instinct: "Instinct",
    feeling: "Feeling",
    emotion: "Emotion",
    passion: "Passion",
    desire: "Desire",
    intention: "Intention",
    will: "Will",
    choice: "Choice",
    freedom: "Freedom",
    liberty: "Liberty",
    independence: "Independence",
    autonomy: "Autonomy",
    sovereignty: "Sovereignty",
    
    // Truth in Time - Temporal Understanding
    time: "Time",
    moment: "Moment",
    present: "Present",
    now: "Now",
    future: "Future",
    past: "Past",
    history: "History",
    memory: "Memory",
    experience: "Experience",
    journey: "Journey",
    path: "Path",
    way: "Way",
    direction: "Direction",
    course: "Course",
    flow: "Flow",
    rhythm: "Rhythm",
    pattern: "Pattern",
    sequence: "Sequence",
    order: "Order",
    chaos: "Chaos",
    complexity: "Complexity",
    simplicity: "Simplicity",
    clarity: "Clarity",
    focus: "Focus",
    attention: "Attention",
    concentration: "Concentration",
    meditation: "Meditation",
    reflection: "Reflection",
    contemplation: "Contemplation",
    
    // Truth in Knowledge - Intellectual Pursuits
    knowledge: "Knowledge",
    learning: "Learning",
    education: "Education",
    study: "Study",
    research: "Research",
    discovery: "Discovery",
    exploration: "Exploration",
    investigation: "Investigation",
    analysis: "Analysis",
    synthesis: "Synthesis",
    understanding: "Understanding",
    comprehension: "Comprehension",
    insight: "Insight",
    revelation: "Revelation",
    epiphany: "Epiphany",
    realization: "Realization",
    recognition: "Recognition",
    acknowledgment: "Acknowledgment",
    acceptance: "Acceptance",
    validation: "Validation",
    confirmation: "Confirmation",
    proof: "Proof",
    evidence: "Evidence",
    facts: "Facts",
    data: "Data",
    information: "Information",
    wisdom: "Wisdom",
    
    // Application Interface
    addProduct: "Add Product",
    productName: "Product Name",
    category: "Category",
    price: "Price",
    quantity: "Quantity",
    description: "Description",
    image: "Image",
    save: "Save",
    cancel: "Cancel",
    submit: "Submit",
    edit: "Edit",
    delete: "Delete",
    update: "Update",
    create: "Create",
    remove: "Remove",
    add: "Add",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    view: "View",
    show: "Show",
    hide: "Hide",
    select: "Select",
    choose: "Choose",
    pick: "Pick",
    options: "Options",
    settings: "Settings",
    preferences: "Preferences",
    configuration: "Configuration",
    customization: "Customization",
    personalization: "Personalization",
    
    // Status & Feedback
    loading: "Loading...",
    saving: "Saving...",
    success: "Success!",
    error: "Error",
    warning: "Warning",
    info: "Information",
    confirm: "Confirm",
    complete: "Complete",
    finished: "Finished",
    done: "Done",
    ready: "Ready",
    available: "Available",
    unavailable: "Unavailable",
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    processing: "Processing",
    completed: "Completed",
    failed: "Failed",
    cancelled: "Cancelled",
    
    // User Roles
    farmer: "Farmer",
    buyer: "Buyer",
    admin: "Administrator",
    cooperative: "Cooperative",
    agent: "Agent",
    manager: "Manager",
    member: "Member",
    guest: "Guest",
    user: "User",
    customer: "Customer",
    client: "Client",
    partner: "Partner",
    supplier: "Supplier",
    vendor: "Vendor",
    
    // Common Actions
    login: "Login",
    logout: "Logout",
    register: "Register",
    signup: "Sign Up",
    signin: "Sign In",
    signout: "Sign Out",
    continue: "Continue",
    back: "Back",
    next: "Next",
    previous: "Previous",
    skip: "Skip",
    finish: "Finish",
    start: "Start",
    stop: "Stop",
    pause: "Pause",
    resume: "Resume",
    retry: "Retry",
    refresh: "Refresh",
    reload: "Reload",
    reset: "Reset",
    clear: "Clear",
    close: "Close",
    open: "Open",
    
    // Messages & Notifications
    welcome: "Welcome",
    goodbye: "Goodbye",
    thankYou: "Thank You",
    please: "Please",
    sorry: "Sorry",
    excuse: "Excuse",
    apology: "Apology",
    congratulations: "Congratulations",
    wellDone: "Well Done!",
    excellent: "Excellent!",
    great: "Great!",
    good: "Good!",
    bad: "Bad!",
    terrible: "Terrible!",
    
    // Time & Date
    today: "Today",
    yesterday: "Yesterday",
    tomorrow: "Tomorrow",
    now: "Now",
    never: "Never",
    always: "Always",
    sometimes: "Sometimes",
    often: "Often",
    rarely: "Rarely",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    yearly: "Yearly",
    morning: "Morning",
    afternoon: "Afternoon",
    evening: "Evening",
    night: "Night",
    
    // Numbers & Quantities
    one: "One",
    two: "Two",
    three: "Three",
    four: "Four",
    five: "Five",
    many: "Many",
    few: "Few",
    some: "Some",
    all: "All",
    none: "None",
    zero: "Zero",
    first: "First",
    last: "Last",
    next: "Next",
    previous: "Previous",
    
    // Quality & Condition
    new: "New",
    old: "Old",
    fresh: "Fresh",
    expired: "Expired",
    valid: "Valid",
    invalid: "Invalid",
    correct: "Correct",
    incorrect: "Incorrect",
    true: "True",
    false: "False",
    right: "Right",
    wrong: "Wrong",
    yes: "Yes",
    no: "No",
    maybe: "Maybe",
    sure: "Sure",
    certain: "Certain",
    uncertain: "Uncertain",
    possible: "Possible",
    impossible: "Impossible",
    
    // Location & Geography
    location: "Location",
    address: "Address",
    city: "City",
    country: "Country",
    region: "Region",
    area: "Area",
    zone: "Zone",
    district: "District",
    province: "Province",
    near: "Near",
    far: "Far",
    here: "Here",
    there: "There",
    everywhere: "Everywhere",
    somewhere: "Somewhere",
    nowhere: "Nowhere",
    online: "Online",
    offline: "Offline",
    
    // Technical & System
    system: "System",
    application: "Application",
    platform: "Platform",
    website: "Website",
    server: "Server",
    database: "Database",
    network: "Network",
    connection: "Connection",
    internet: "Internet",
    technology: "Technology",
    software: "Software",
    hardware: "Hardware",
    device: "Device",
    computer: "Computer",
    mobile: "Mobile",
    tablet: "Tablet",
    
    // Economic & Business
    price: "Price",
    cost: "Cost",
    free: "Free",
    paid: "Paid",
    cheap: "Cheap",
    expensive: "Expensive",
    affordable: "Affordable",
    valuable: "Valuable",
    worthless: "Worthless",
    profit: "Profit",
    loss: "Loss",
    income: "Income",
    expense: "Expense",
    budget: "Budget",
    savings: "Savings",
    investment: "Investment",
    return: "Return",
    refund: "Refund",
    discount: "Discount",
    offer: "Offer",
    deal: "Deal",
    bargain: "Bargain",
    sale: "Sale",
    
    // Communication
    message: "Message",
    email: "Email",
    phone: "Phone",
    contact: "Contact",
    call: "Call",
    text: "Text",
    chat: "Chat",
    talk: "Talk",
    speak: "Speak",
    listen: "Listen",
    read: "Read",
    write: "Write",
    send: "Send",
    receive: "Receive",
    reply: "Reply",
    forward: "Forward",
    
    // Help & Support
    help: "Help",
    support: "Support",
    assist: "Assist",
    guide: "Guide",
    tutorial: "Tutorial",
    instructions: "Instructions",
    manual: "Manual",
    documentation: "Documentation",
    faq: "FAQ",
    about: "About",
    info: "Info",
    details: "Details",
    more: "More",
    less: "Less",
    
    // Security & Privacy
    security: "Security",
    privacy: "Privacy",
    safety: "Safety",
    protection: "Protection",
    password: "Password",
    account: "Account",
    profile: "Profile",
    settings: "Settings",
    permissions: "Permissions",
    access: "Access",
    login: "Login",
    logout: "Logout",
    authenticate: "Authenticate",
    authorize: "Authorize",
    verify: "Verify",
    confirm: "Confirm",
    
    // Health & Wellness
    health: "Health",
    wellness: "Wellness",
    fitness: "Fitness",
    nutrition: "Nutrition",
    exercise: "Exercise",
    diet: "Diet",
    medical: "Medical",
    medicine: "Medicine",
    care: "Care",
    treatment: "Treatment",
    recovery: "Recovery",
    healing: "Healing",
    prevention: "Prevention",
    
    // Social & Community
    social: "Social",
    community: "Community",
    group: "Group",
    team: "Team",
    family: "Family",
    friends: "Friends",
    neighbors: "Neighbors",
    members: "Members",
    participants: "Participants",
    followers: "Followers",
    following: "Following",
    shares: "Shares",
    likes: "Likes",
    comments: "Comments",
    reviews: "Reviews",
    ratings: "Ratings",
    
    // Agriculture Specific
    farm: "Farm",
    farmer: "Farmer",
    crops: "Crops",
    harvest: "Harvest",
    planting: "Planting",
    seeds: "Seeds",
    soil: "Soil",
    water: "Water",
    fertilizer: "Fertilizer",
    pesticide: "Pesticide",
    equipment: "Equipment",
    tools: "Tools",
    machinery: "Machinery",
    livestock: "Livestock",
    animals: "Animals",
    poultry: "Poultry",
    cattle: "Cattle",
    goats: "Goats",
    sheep: "Sheep",
    pigs: "Pigs",
    chickens: "Chickens",
    eggs: "Eggs",
    milk: "Milk",
    meat: "Meat",
    dairy: "Dairy",
    grains: "Grains",
    vegetables: "Vegetables",
    fruits: "Fruits",
    organic: "Organic",
    natural: "Natural",
    sustainable: "Sustainable",
    traditional: "Traditional",
    modern: "Modern",
    
    // Marketplace
    market: "Market",
    marketplace: "Marketplace",
    shop: "Shop",
    store: "Store",
    buy: "Buy",
    sell: "Sell",
    trade: "Trade",
    exchange: "Exchange",
    purchase: "Purchase",
    order: "Order",
    cart: "Cart",
    checkout: "Checkout",
    payment: "Payment",
    delivery: "Delivery",
    shipping: "Shipping",
    pickup: "Pickup",
    inventory: "Inventory",
    stock: "Stock",
    supply: "Supply",
    demand: "Demand",
    
    // Final Truth Principles
    integrity: "Integrity in all transactions",
    honesty: "Honesty in all dealings",
    transparency: "Transparency in all operations",
    quality: "Quality in all products",
    service: "Service to all customers",
    respect: "Respect for all participants",
    fairness: "Fairness to all partners",
    trust: "Trust in all relationships",
    excellence: "Excellence in all endeavors"
  },
  
  // Kinyarwanda translations - Truth words in local language
  rw: {
    // Core Navigation
    home: "Ahabanza",
    login: "Injira", 
    register: "Iyandikishe", 
    dashboard: "Panyaporosora",
    products: "Ibiribwa",
    orders: "Amabwirize",
    profile: "Profaili",
    logout: "Sohoka",
    
    // Truth Words - About Others & Integrity
    truth: "Ukwishikiza",
    honesty: "Ukwishikiza",
    integrity: "Ubumwe",
    transparency: "Ubusanzi",
    fairness: "Uburwayane",
    respect: "Kunenga",
    trust: "Ukwihangira",
    authenticity: "Ukwishikiza",
    accountability: "Ukuntu",
    responsibility: "Urwego",
    community: "Abanyi",
    collaboration: "Ubufashanye",
    support: "Gushigisha",
    empowerment: "Kwihangira",
    equality: "Uburinganije",
    justice: "Ubutabera",
    service: "Serivisi",
    dedication: "Ugushikirwa",
    commitment: "Ubwiranye",
    excellence: "Ukurihe",
    quality: "Ubwiza",
    value: "Agaciro",
    principles: "Amategeko",
    ethics: "Ibyisho",
    morals: "Imyitwaro",
    character: "Ubwenge",
    virtue: "Imyitwaro",
    wisdom: "Ubumenyi",
    knowledge: "Umenyi",
    understanding: "Gukunda",
    compassion: "Ubunyangiwe",
    kindness: "Ubunyangiwe",
    generosity: "Ugushikirwa",
    patience: "Ukunenga",
    perseverance: "Ugukora",
    courage: "Ubwenge",
    strength: "Umuhamavu",
    resilience: "Ukwihangira",
    hope: "Utsinda",
    faith: "Ukwihangira",
    love: "Urukundo",
    peace: "Amanzi",
    unity: "Kubunganirwa",
    harmony: "Ihuze",
    balance: "Ihuze",
    growth: "Kukura",
    learning: "Kwiga",
    teaching: "Gukiga",
    sharing: "Gusangiza",
    giving: "Guhaha",
    receiving: "Kakira",
    gratitude: "Ushukirwa",
    humility: "Ubwigenge",
    forgiveness: "Ugusaba",
    reconciliation: "Kubunganirwa",
    healing: "Gukira",
    restoration: "Kugarura",
    renewal: "Gukora",
    transformation: "Guhindura",
    
    // About Others - Building Relationships
    connection: "Uhuze",
    relationship: "Ubumwe",
    friendship: "Ubunyangiwe",
    partnership: "Ubufashanye",
    cooperation: "Ubufashanye",
    teamwork: "Akazi ku mubiri",
    communication: "Ukwihangiriza",
    listening: "Kumva",
    empathy: "Kunenga",
    acceptance: "Kwemera",
    tolerance: "Guhangira",
    inclusion: "Gushyingurwa",
    belonging: "Kuba muri",
    welcome: "Murakaza neza",
    hospitality: "Ubugabiza",
    care: "Gukunda",
    concern: "Ukuntu",
    attention: "Amezi",
    presence: "Uwo muri",
    engagement: "Gukunda",
    
    // Application Interface
    addProduct: "Ongeraho ibiribwa",
    productName: "Izina ry'ibiribwa",
    category: "Itsinda",
    price: "Igiciro",
    quantity: "Igiteranyo",
    description: "Ibisobanuro",
    image: "Ishusho",
    save: "Bika",
    cancel: "Kureka",
    submit: "Ongeraho",
    edit: "Guhindura",
    delete: "Siba",
    update: "Gukura",
    create: "Kurema",
    remove: "Siba",
    search: "Shakisha",
    filter: "Muyunguruzo",
    sort: "Itonderanya",
    
    // Status & Feedback
    loading: "Itarikiza...",
    saving: "Bika...",
    success: "Byakunze!",
    error: "Ikosa",
    warning: "Iburabishije",
    info: "Ibisobanuro",
    confirm: "Emeza",
    complete: "Byarangiye",
    failed: "Byanze",
    
    // Help & UI Actions
    closeHelp: "Gufunga Ifashyamba",
    getHelp: "Gushaka Ubufasha",
    close: "Gufunga",
    help: "Ubufasha",
    quickSteps: "Intambwe zikurikiranye",
    commonIssues: "Ibibazo Bisanzwe",
    quickTips: "Inama zikurikiranye",
    viewFullHelpGuide: "Kureba Ifashyamba Ryose",
    helpAvailable: "Ubufasha Bwabonetse",
    hide: "Kuhisha",
    show: "Kwerekana",
    
    // User Roles
    farmer: "Umuhinzi",
    buyer: "Mukiri",
    admin: "Umuyobozi",
    cooperative: "Itsinda ry'ubufashanye",
    
    // Economic & Business
    price: "Igiciro",
    profit: "Inyungu",
    income: "Amanota",
    affordable: "Bishoboka",
    valuable: "Bifuzi",
    
    // Agriculture Specific
    farm: "Shamba",
    crops: "Ibiribwa",
    harvest: "Ukurura",
    planting: "Guteranya",
    organic: "Biya muri rusange",
    sustainable: "Bihanganye",
    marketplace: "Isoko"
  },
  
  // French translations - Truth words in French
  fr: {
    // Core Navigation
    home: "Accueil",
    login: "Connexion", 
    register: "S'inscrire",
    dashboard: "Tableau de bord",
    products: "Produits",
    orders: "Commandes",
    profile: "Profil",
    logout: "Déconnexion",
    
    // Truth Words - About Others & Integrity
    truth: "Vérité",
    honesty: "Honnêteté",
    integrity: "Intégrité",
    transparency: "Transparence",
    fairness: "Équité",
    respect: "Respect",
    trust: "Confiance",
    authenticity: "Authenticité",
    accountability: "Responsabilité",
    responsibility: "Responsabilité",
    community: "Communauté",
    service: "Service",
    excellence: "Excellence",
    quality: "Qualité",
    
    // Application Interface
    addProduct: "Ajouter un produit",
    productName: "Nom du produit",
    category: "Catégorie",
    price: "Prix",
    quantity: "Quantité",
    save: "Enregistrer",
    cancel: "Annuler",
    submit: "Soumettre",
    
    // User Roles
    farmer: "Agriculteur",
    buyer: "Acheteur",
    admin: "Administrateur",
    
    // Economic & Business
    marketplace: "Marché",
    buy: "Acheter",
    sell: "Vendre",
    order: "Commande",
    cart: "Panier",
    payment: "Paiement",
    delivery: "Livraison",
    
    // Agriculture Specific
    crops: "Cultures",
    harvest: "Récolte",
    organic: "Biologique",
    sustainable: "Durable"
  }
};

// Get current language
const getCurrentLanguage = () => {
  return localStorage.getItem('language') || 'en';
};

// Set language
const setLanguage = (lang) => {
  localStorage.setItem('language', lang);
  window.dispatchEvent(new CustomEvent('languageChanged', { detail: { lang } }));
};

// Main translation function
const translate = (key) => {
  const lang = getCurrentLanguage();
  return translations[lang]?.[key] || key;
};

// Export functions
export {
  translate,
  getCurrentLanguage,
  setLanguage
};
